  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the code for Landingpage
      # - mocha test.js
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
    - index.html
    - updateUser.html
    - favicon.ico
    - style.css
    - bmwitcup.js
    - bmwitcup_UpdateUser.js
    - img/*